# -*- coding: utf-8 -*-
"""święta .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vDNWMxWk-HFlRLHUhZUvpNJP5seBdf0
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np # Dodane do pomocy przy kształtach

def draw_detailed_santa_claus_with_legs_and_many_gifts():
    """Rysuje szczegółowego Świętego Mikołaja z nogami, butami, rękami, pełną twarzą i wieloma prezentami w worku."""

    # 1. Konfiguracja płótna
    fig, ax = plt.subplots(figsize=(10, 10)) # Zwiększamy rozmiar dla nóg i więcej prezentów
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 12)
    ax.set_aspect('equal')
    ax.axis('off')

    # Zmienne dla łatwiejszej zmiany położenia i kolorów
    center_x = 5
    head_y = 7.5
    body_y_start = 3
    suit_color = '#D62828' # Czerwony strój Mikołaja
    skin_color = '#FAD0BB' # Kolor skóry
    beard_color = 'white'
    belt_color = 'black'
    buckle_color = '#FFC300' # Złoty

    # --- 2. NOGI I BUTY (NOWA SEKCJA) ---
    leg_width = 1.2
    leg_height = 2
    foot_length = 1.5
    foot_height = 0.5

    # Lewa noga
    leg_left_x = center_x - 1.5
    leg_left = patches.Rectangle((leg_left_x, body_y_start - leg_height), leg_width, leg_height, facecolor=suit_color, edgecolor='black', linewidth=1.5, zorder=1)
    ax.add_patch(leg_left)
    # Futro na dole lewej nogi
    fur_left_leg = patches.Rectangle((leg_left_x, body_y_start - leg_height - 0.2), leg_width, 0.4, facecolor='white', edgecolor='black', linewidth=1.5, zorder=2)
    ax.add_patch(fur_left_leg)
    # Lewy but
    foot_left = patches.Rectangle((leg_left_x - 0.2, body_y_start - leg_height - foot_height - 0.2), foot_length, foot_height, facecolor='#654321', edgecolor='black', linewidth=1.5, zorder=1)
    ax.add_patch(foot_left)

    # Prawa noga
    leg_right_x = center_x + 1.5 - leg_width
    leg_right = patches.Rectangle((leg_right_x, body_y_start - leg_height), leg_width, leg_height, facecolor=suit_color, edgecolor='black', linewidth=1.5, zorder=1)
    ax.add_patch(leg_right)
    # Futro na dole prawej nogi
    fur_right_leg = patches.Rectangle((leg_right_x, body_y_start - leg_height - 0.2), leg_width, 0.4, facecolor='white', edgecolor='black', linewidth=1.5, zorder=2)
    ax.add_patch(fur_right_leg)
    # Prawy but
    foot_right = patches.Rectangle((leg_right_x - 0.2, body_y_start - leg_height - foot_height - 0.2), foot_length, foot_height, facecolor='#654321', edgecolor='black', linewidth=1.5, zorder=1)
    ax.add_patch(foot_right)


    # --- 3. CIAŁO (Trapez) ---
    body_points = [
        (center_x - 2, body_y_start),
        (center_x + 2, body_y_start),
        (center_x + 1.5, head_y - 1.5),
        (center_x - 1.5, head_y - 1.5)
    ]
    body = patches.Polygon(body_points, closed=True, facecolor=suit_color, edgecolor='black', linewidth=1.5)
    ax.add_patch(body)

    # --- 4. PASEK i KLAMRA ---
    belt_y = body_y_start + 1.5
    belt = patches.Rectangle((center_x - 2, belt_y), 4, 0.5, facecolor=belt_color, edgecolor='black', linewidth=1)
    ax.add_patch(belt)
    buckle = patches.Rectangle((center_x - 0.5, belt_y + 0.1), 1, 0.3, facecolor=buckle_color, edgecolor='black', linewidth=1)
    ax.add_patch(buckle)

    # --- 5. RĘCE ---
    arm_y = head_y - 2.5

    # Lewa ręka
    arm_left = patches.Rectangle((center_x - 2.5, arm_y), 1, 0.5, angle=20, facecolor=suit_color, edgecolor='black', linewidth=1)
    ax.add_patch(arm_left)
    hand_left = patches.Circle((center_x - 2.8, arm_y + 0.5), 0.4, facecolor='white', edgecolor='black', linewidth=1)
    ax.add_patch(hand_left)

    # Prawa ręka
    arm_right = patches.Rectangle((center_x + 1.5, arm_y), 1, 0.5, angle=-20, facecolor=suit_color, edgecolor='black', linewidth=1)
    ax.add_patch(arm_right)
    hand_right = patches.Circle((center_x + 2.8, arm_y + 0.5), 0.4, facecolor='white', edgecolor='black', linewidth=1)
    ax.add_patch(hand_right)

    # --- 6. TWARZ I BRODA ---
    main_beard = patches.Circle((center_x, head_y - 1), 1.8, facecolor=beard_color, edgecolor='black', linewidth=1.5, zorder=5)
    ax.add_patch(main_beard)

    face = patches.Circle((center_x, head_y), 1.2, facecolor=skin_color, edgecolor='black', linewidth=1.5, zorder=7)
    ax.add_patch(face)

    # USZY
    ear_left = patches.Circle((center_x - 1.3, head_y + 0.1), 0.3, facecolor=skin_color, edgecolor='black', linewidth=1, zorder=6)
    ax.add_patch(ear_left)
    ear_right = patches.Circle((center_x + 1.3, head_y + 0.1), 0.3, facecolor=skin_color, edgecolor='black', linewidth=1, zorder=6)
    ax.add_patch(ear_right)

    # Wąsy
    mustache_left = patches.Circle((center_x - 0.6, head_y + 0.1), 0.6, facecolor=beard_color, edgecolor='black', linewidth=1.5, zorder=6)
    ax.add_patch(mustache_left)
    mustache_right = patches.Circle((center_x + 0.6, head_y + 0.1), 0.6, facecolor=beard_color, edgecolor='black', linewidth=1.5, zorder=6)
    ax.add_patch(mustache_right)

    # NOS
    nose = patches.Circle((center_x, head_y + 0.1), 0.25, facecolor='pink', edgecolor='black', linewidth=1, zorder=9)
    ax.add_patch(nose)

    # USTA
    mouth_arc = patches.Arc((center_x, head_y - 0.2), width=0.8, height=0.4, angle=0, theta1=200, theta2=340, color='red', linewidth=2, zorder=10)
    ax.add_patch(mouth_arc)

    # Oczy
    ax.plot(center_x - 0.4, head_y + 0.5, 'o', markersize=6, color='black', zorder=9)
    ax.plot(center_x + 0.4, head_y + 0.5, 'o', markersize=6, color='black', zorder=9)

    # --- 7. KAPELUSZ ---
    cap_top_y = head_y + 3.5

    cap_base = patches.Rectangle((center_x - 1.5, head_y + 1), 3, 0.5, facecolor='white', edgecolor='black', linewidth=1.5, zorder=8)
    ax.add_patch(cap_base)
    cap_main = patches.Polygon([
        (center_x - 1.5, head_y + 1.5),
        (center_x + 1.5, head_y + 1.5),
        (center_x, cap_top_y)
    ], closed=True, facecolor=suit_color, edgecolor='black', linewidth=1.5, zorder=7)
    ax.add_patch(cap_main)
    pom_pom = patches.Circle((center_x, cap_top_y), 0.35, facecolor='white', edgecolor='black', linewidth=1.5, zorder=8)
    ax.add_patch(pom_pom)

    # --- 8. WOREK Z WIELOMA PREZENTAMI (Zaktualizowana sekcja) ---
    bag_x = center_x + 3.5
    bag_y = body_y_start - 1 # Worek nieco niżej, żeby był obok nóg

    # Kształt worka (bardziej zaokrąglony prostokąt lub duża elipsa)
    bag = patches.Ellipse((bag_x, bag_y + 2), 3, 5, angle=-15, facecolor='#8B4513', edgecolor='black', linewidth=1.5, zorder=2)
    ax.add_patch(bag)

    # Prezenty wystające z worka
    # Lista kolorów, aby prezenty były różnorodne
    gift_colors = ['#FFC0CB', '#90EE90', '#ADD8E6', '#FFD700', '#DDA0DD', '#FF6347'] # Pastelowe/jasne kolory
    ribbon_colors = ['#FF0000', '#008000', '#0000FF', '#8B4513', '#800080', '#DAA520'] # Kontrastowe wstążki

    # Funkcja pomocnicza do rysowania prezentu
    def add_gift(x, y, width, height, gift_color, ribbon_color, rotation=0):
        gift = patches.Rectangle((x, y), width, height, angle=rotation, facecolor=gift_color, edgecolor='black', linewidth=0.8, zorder=3)
        ax.add_patch(gift)

        # Pionowa wstążka
        ribbon_v = patches.Rectangle((x + width/2 - 0.1, y), 0.2, height, angle=rotation, facecolor=ribbon_color, zorder=4)
        ax.add_patch(ribbon_v)
        # Pozioma wstążka
        ribbon_h = patches.Rectangle((x, y + height/2 - 0.1), width, 0.2, angle=rotation, facecolor=ribbon_color, zorder=4)
        ax.add_patch(ribbon_h)

    # Pozycja i rozmiar prezentów
    # (x, y, width, height, kolor_prezentu, kolor_wstążki, rotacja)
    add_gift(bag_x - 0.5, bag_y + 4.5, 1.0, 1.0, gift_colors[0], ribbon_colors[0], 10)
    add_gift(bag_x + 0.8, bag_y + 4.2, 0.8, 0.8, gift_colors[1], ribbon_colors[1], -15)
    add_gift(bag_x - 1.2, bag_y + 3.8, 1.1, 0.9, gift_colors[2], ribbon_colors[2], 5)
    add_gift(bag_x + 0.1, bag_y + 3.5, 0.7, 0.7, gift_colors[3], ribbon_colors[3], 20)
    add_gift(bag_x - 0.8, bag_y + 3.0, 0.9, 0.9, gift_colors[4], ribbon_colors[4], -5)
    add_gift(bag_x + 0.5, bag_y + 2.8, 0.6, 0.6, gift_colors[5], ribbon_colors[5], 15)

    # 9. Wyświetlenie
    plt.title("Szczegółowy Święty Mikołaj z nogami i mnóstwem prezentów")
    plt.show()

# Uruchomienie funkcji
draw_detailed_santa_claus_with_legs_and_many_gifts()